// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteSQLWithPage(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function ExportExcelBySQL(arg1:string):Promise<string>;

export function GetCurrentSQL():Promise<string>;

export function OpenExcel():Promise<string>;
