// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteSQL(arg1) {
  return window['go']['main']['App']['ExecuteSQL'](arg1);
}

export function OpenExcel() {
  return window['go']['main']['App']['OpenExcel']();
}

export function SaveResult() {
  return window['go']['main']['App']['SaveResult']();
}
