// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteSQL(arg1:string):Promise<Record<string, any>>;

export function OpenExcel():Promise<string>;

export function SaveResult():Promise<string>;
