// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteSQLWithPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSQLWithPage'](arg1, arg2, arg3);
}

export function ExportExcelBySQL(arg1) {
  return window['go']['main']['App']['ExportExcelBySQL'](arg1);
}

export function GetCurrentSQL() {
  return window['go']['main']['App']['GetCurrentSQL']();
}

export function OpenExcel() {
  return window['go']['main']['App']['OpenExcel']();
}
